name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci || npm i

      - name: Set Vite base for pages
        run: |
          if [[ "${{ github.repository_owner }}" == "${{ github.event.repository.name }}" ]]; then
            # user/organization pages repo -> root deployment
            echo "VITE_BASE=/" >> $GITHUB_ENV
          else
            echo "VITE_BASE=/${{ github.event.repository.name }}/" >> $GITHUB_ENV
          fi

      - name: Add CNAME if custom domain is configured
        if: ${{ secrets.CUSTOM_DOMAIN != '' }}
        run: |
          mkdir -p dist
          echo "${{ secrets.CUSTOM_DOMAIN }}" > dist/CNAME

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
